### ISSUE TITLE
Unable to add spaces between buttons to the toolbar in Waterfox 56

### ISSUE THREAD

**Issue by Telmesomething** [Aris-t2/ClassicThemeRestorer#383]
After installing CTR in Waterfox 56, I'm unable to add spaces between the buttons on the toolbar. Dragging a space from the Customize menu takes it up there, but is doesn't remain in place. Same goes for flexible spaces. 

In the top half of the attached screenshot a space has been dragged to the spot indicated by the red arrow, but after releasing the mouse button, the space has been removed and has reappeared in the Customize panel. 

![ctr_spaces](https://user-images.githubusercontent.com/33827636/33517086-039bb8dc-d77e-11e7-9bf3-32afa9364bbd.PNG)

Here's what it looks like after closing the Customize menu.

![ctr_spaces after closing custimize](https://user-images.githubusercontent.com/33827636/33517168-8778af2e-d77f-11e7-80c0-bd1b3dd195bc.PNG)

**Comment by Aris-t2** [comment]
Waterfox 56 and Firefox 56 do not support spaces, flexible spaces and separators anymore.

**Comment by Telmesomething** [comment]
> Waterfox 56 and Firefox 56 do not support spaces, flexible spaces and separators anymore.

Thanks for letting me know Aris.

It's a real shame then that the Waterfox developer decided to base it on FF56 because not having the option to add separators in between toolbar buttons means that they're all cluttered up together.

**Comment by mzso** [comment]
[**@Telmesomething**](https://github.com/Telmesomething) commented on [2017. dec. 3. 10:11 CET](https://github.com/Aris-t2/ClassicThemeRestorer/issues/383#issuecomment-348750807 "2017-12-03T09:11:51Z - Replied by Github Reply Comments"):
> > Waterfox 56 and Firefox 56 do not support spaces, flexible spaces and separators anymore.
> 
> Thanks for letting me know Aris.
> 
> It's a real shame then that the Waterfox developer decided to base it on FF56 because not having the option to add separators in between toolbar buttons means that they're all cluttered up together.

There's a workaround. Add them via their context menu, then you can move them.

**Comment by grahamperrin** [comment]
> … unable to add …

## Workaround

Whilst customising, use the contextual menu. 

This screenshot was taken after adding a flexible space, divider and space: 

![2017-12-24 14 50 37 customize waterfox - waterfox](https://user-images.githubusercontent.com/192271/34327365-4f626796-e8ba-11e7-970d-20eaab1b6987.png)

**Comment by Telmesomething** [comment]
> There's a workaround. Add them via their context menu, then you can move them.

> Whilst customising, use the contextual menu.

Magic! Just what the doctor ordered. Thanks very much mzso.

Many thanks also to grahamperrin for the screenshot.

**Comment by Aris-t2** [comment]
I think we can keep this open so others can find this workaround too.

**Comment by Telmesomething** [comment]
> I think we can keep this open so others can find this workaround too.

Just as well as it turns out. After adding spaces between toolbar buttons and then closing the Customization menu I noticed I'd missed one between two buttons. On reopening the Customize menu all the separators had disappeared. 

However, after exiting Waterfox and restarting it again, they reappeared. So just a minor anomally.

**Comment by mzso** [comment]
[**@Telmesomething**](https://github.com/Telmesomething) commented on [2017. dec. 25. 11:15 CET](https://github.com/Aris-t2/ClassicThemeRestorer/issues/383#issuecomment-353857755 "2017-12-25T10:15:37Z - Replied by Github Reply Comments"):
> > I think we can keep this open so others can find this workaround too.
> 
> Just as well as it turns out. After adding spaces between toolbar buttons and then closing the Customization menu I noticed I'd missed one between two buttons. On reopening the Customize menu all the separators had disappeared.
> 
> However, after exiting Waterfox and restarting it again, they reappeared. So just a minor anomally.

Yes. This his how it works on v56... You only have the separators the first time. After you switch tabs and back or close/open the customize tab the separators are gone for that session...

**Comment by Aris-t2** [comment]
Firefox runs a code to remove those items once in customizing mode. We are lucky it fails the first time. A shame Waterfox team incorporated this into their browser as they are eager to keep Firefox' rubbish code out of their project.

**Comment by mzso** [comment]
[**@Aris-t2**](https://github.com/Aris-t2) commented on [2017. dec. 25. 13:07 CET](https://github.com/Aris-t2/ClassicThemeRestorer/issues/383#issuecomment-353865019 "2017-12-25T12:07:11Z - Replied by Github Reply Comments"):
> Firefox runs a code to remove those items once in customizing mode. We are lucky it fails the first time. A shame Waterfox team incorporated this into their browser as they are eager to keep Firefox' rubbish code out of their project.

Judging by the answers of the WF dev it might be done in a future update.

**Comment by Telmesomething** [comment]
No need to be concerned about the post I made [here](https://github.com/MrAlex94/Waterfox/issues/333) yesterday Aris. It turned out to be a config setting namely `privacy.resistFingerprinting`. When set to _true_, Waterfox resizes itself on opening. 

I managed to find it after creating a new profile and then restarting it every time I made a change either by adding an extension or making a config change.

**Comment by jemonaff** [comment]
Install "Classic Theme Restorer" then you can find the Flexble toolbar and Space and Separator.
But They will disappear when you exit customize.
If you want to find them, you reboot Waterfox.

**Comment by jemonaff** [comment]
Install "Classic Theme Restorer" then you can find the Flexble toolbar and Space and Separator.
But They will disappear when you exit customize.
If you want to find them, you reboot Waterfox.
![2018-04-17_](https://user-images.githubusercontent.com/24565393/38864528-f9808b58-4275-11e8-8e05-54bdd228eb85.png)

**Comment by jemonaff** [comment]
Install "Classic Theme Restorer" then you can find the Flexble toolbar and Space and Separator.
But They will disappear when you exit customize.
If you want to find them, you reboot Waterfox.
![2018-04-17__](https://user-images.githubusercontent.com/24565393/38864687-677d4470-4276-11e8-81a2-ac226b47c04c.png)

**Comment by mzso** [comment]
[**@jemonaff**](https://github.com/jemonaff) commented on [2018. ápr. 17. 12:35 CEST](https://github.com/Aris-t2/ClassicThemeRestorer/issues/383#issuecomment-381941286 "2018-04-17T10:35:02Z - Replied by Github Reply Comments"):
> Install "Classic Theme Restorer" then you can find the Flexble toolbar and Space and Separator.  
> 
> But They will disappear when you exit customize.  
> 
> If you want to find them, you reboot Waterfox.  

All of this was discussed before, and it doesn't actually work completely. You can only use the context menu to add them.
Also, naturally everyone has CTR installed already, this issue is filed for CTR.

**Comment by vertigo220** [comment]
Hopefully this gets fixed, as it was very frustrating to deal with and wasted a lot of my time figuring it out, but the workaround described here was very helpful, so thank you! I didn't realize at first what was meant by it and thought the items had to be added in order, that it was an issue of not being able to move the spaces around. So I removed all my items then started re-adding them with spaces, and at that point I realized what was meant.

**Comment by vertigo220** [comment]
@Aris-t2 I would agree it's not a high-priority since a restart fixes it, but I wasted a fair amount of time trying to figure out how to fix it before realizing that, and fixing the problem would avoid others having to deal with that as well. Anyways, hopefully by me mentioning it someone else will figure it out a little easier, and it might be useful to know if others have the issue without CTR or in other setups. I've added both the issues to my list of things to report.

**Comment by Aris-t2** [comment]
Could you open a new bug for this and run some tests to ensure this issue can be reproduced step by step?

Use Firefox 56 portable or Waterfox 56 portable (creating a new browser profile), install CTR, install one of the affected add-ons and test, if the issue still occurs in that environment.
(I'm asking for this, because I run a quick test with DownThemAll add-on and the mentioned issue did not occur for me).

**Comment by vertigo220** [comment]
Well, I just tried with a fresh install and couldn't reproduce it. Not sure if it was a conflict with another addon or just some really obscure fluke bug or what, but since it doesn't seem to be readily reproducible and since it's fixed with a browser restart, and it hasn't recurred since, I'd say it's not worth worrying about. If someone else comes along with the same issue, maybe they can provide more info that can help narrow it down, but if nothing else hopefully this will help them figure out to restart their browser without spending as much time as I did trying to figure out other solutions.

**Comment by grahamperrin** [comment]
> Could you open a new bug for this …

Do you mean, the disappearance (from available buttons) after first use of _Customise_?

**Comment by Diverso1982** [comment]
Does the problem still exist? Can we add separator anyhow in FF63?

**Comment by Diverso1982** [comment]
I added separators instead of flexible spaces thanks to Aris' _flex_space_on_navbar_replace_with_separator.css_. I resized them to 10px instead of 1px, that is perfect. And the last I need - how to change its' color? I need them to be fully transparent.

![default](https://user-images.githubusercontent.com/45521895/49332830-62380100-f5c5-11e8-8d97-ff0a683ca1a8.PNG)

**Comment by Aris-t2** [comment]
Fully transparent would make them invisible, but if that is what you are looking for, replace the "red" with "transparent":

```css
#main-window:not([customizing]) #nav-bar toolbarspring {
  -moz-appearance: unset !important;
  min-width: 0px !important;
  max-width: 0px !important;
  border-right: 1px solid red !important;
  -moz-margin-start: 5px !important;
  -moz-margin-end: 5px !important;
}
```

**Comment by grahamperrin** [comment]
Workaround (a complementary legacy extension)

### Puzzle Bars

- https://web.archive.org/web/20171102000813/https://addons.mozilla.org/en-US/firefox/addon/puzzle-toolbars/
- https://web.archive.org/web/20181018042350/https://addons.cdn.mozilla.net/user-media/addons/439154/puzzle_bars-2.1.17-fx.xpi?filehash=sha256:9da4fdd5f51e978a733ce99bedcb8f6fe0ce478e7078d3a5a53165ae856e6396

In the Classic Add-ons Archive: 

- caa:addon/puzzle-toolbars
- https://ca-archive.biz.tm/storage/439/439154/puzzle_bars-2.1.17-fx.xpi
